"""Golden-file tests: full-layout generator output, compared against recorded
files in tests/goldens/ (a.k.a. "golden files").

These are standalone tests: generators are called directly on parsed layouts (no
`dist/`, no build step). The goldens were generated on commit a9724bf, so every
deliberate fix shows up as a small, reviewable diff. Regenerate intentionally
with:

    KALAMINE_UPDATE_GOLDENS=1 pixi run -e dev python -m pytest tests/test_goldens.py

The generator functions return plain text (Python strings). The UTF-16LE + CR/LF
encoding of the real `.klc` files happens by CLI when writing the files. The
goldens, however, are stored as UTF-8 text (and protected from git mangling via
`-text` in `.gitattributes`) because we don't need to store them as UTF-16, as
we compare them as strings.

Note: the `ansi`, `intl` and `prog` KLC goldens were recorded later than the
rest due to an issue. They had `locale = "us"`, which is not a key of
`win_locales.yaml` (KLC generation failed, and `build_all` silently left an
empty .klc behind). They got added when the entry was fixed to `en-US`.
"""

import os
import re
from pathlib import Path

import pytest

from kalamine.generators import klc, web, xkb
from kalamine.layout import KeyboardLayout, load_layout

REPO_ROOT = Path(__file__).parent.parent
GOLDEN_DIR = Path(__file__).parent / "goldens"
LAYOUTS = ["ansi", "intl", "prog", "diacra"]
OUTPUTS = ["klc", "xkb_keymap", "xkb_symbols", "json"]

# The templates embed the generation date as a comment ("Generated by kalamine
# on YYYY-MM-DD", see kalamine/template.py). Normalize it on both sides so
# goldens stay valid across runs. A change to the surrounding format still shows
# up as a diff.
DATE_LINE = re.compile(r"Generated by kalamine on [0-9]{4}-[0-9]{2}-[0-9]{2}")


def normalize(text: str) -> str:
    return DATE_LINE.sub("Generated by kalamine on DATE", text)


def build_layout(layout_name: str) -> KeyboardLayout:
    descriptor = REPO_ROOT / "layouts" / f"{layout_name}.toml"
    return KeyboardLayout(load_layout(descriptor))


def generate(layout: KeyboardLayout, output_name: str) -> str:
    if output_name == "klc":
        return klc.klc(layout)
    if output_name == "xkb_keymap":
        return xkb.xkb_keymap(layout)
    if output_name == "xkb_symbols":
        return xkb.xkb_symbols(layout)
    if output_name == "json":
        return web.pretty_json(layout)
    raise ValueError(f"unknown output: {output_name}")


@pytest.mark.parametrize("output_name", OUTPUTS)
@pytest.mark.parametrize("layout_name", LAYOUTS)
def test_golden(layout_name: str, output_name: str) -> None:
    text = normalize(generate(build_layout(layout_name), output_name))
    golden_path = GOLDEN_DIR / f"{layout_name}.{output_name}"

    if os.environ.get("KALAMINE_UPDATE_GOLDENS"):
        golden_path.parent.mkdir(parents=True, exist_ok=True)
        golden_path.write_text(text, encoding="utf-8", newline="\n")
        return

    expected = golden_path.read_text(encoding="utf-8")
    assert text == expected, f"output drift in {golden_path.name}"


def klc_dead_key_ids(layout_name: str) -> list:
    klc_text = generate(build_layout(layout_name), "klc")
    return re.findall(r"^DEADKEY\t([0-9A-F]{4})$", klc_text, flags=re.MULTILINE)


def klc_virtual_keys(layout_name: str) -> list:
    klc_text = generate(build_layout(layout_name), "klc")
    entries = re.findall(r"^[0-9A-F]{2}\t(\S+)\t[01]\t", klc_text, flags=re.MULTILINE)
    return entries


@pytest.mark.parametrize("layout_name", LAYOUTS)
def test_no_dead_key_id_twice(layout_name: str) -> None:
    """Invariant: two dead keys must never share a 4-hex-digit ID in a KLC.

    Windows keeps only one table per ID. Without a fix, the `diacra` layout
    suffers from this. The 1dk identity (`'`) and dead acute (`*´`) both map to
    DEADKEY 0027 in KLC.
    """
    ids = klc_dead_key_ids(layout_name)
    if len(ids) != len(set(ids)):
        pytest.xfail("known DEADKEY 0027 collision on the unfixed baseline")
    assert len(ids) == len(set(ids)), f"duplicate dead-key IDs: {sorted(ids)}"


@pytest.mark.parametrize("layout_name", LAYOUTS)
def test_no_virtual_key_twice(layout_name: str) -> None:
    """Invariant: no virtual key may be assigned to two scan codes."""
    virtual_keys = klc_virtual_keys(layout_name)
    assert len(virtual_keys) == len(set(virtual_keys)), (
        f"duplicate virtual keys: {sorted(set(virtual_keys))}"
    )
